export const ADD_BLOG_PAGE_LOADING = 'ADD_BLOG_PAGE_LOADING';
export const ADD_BLOG_PAGE_LOADED = 'ADD_BLOG_PAGE_LOADED';
export const ADD_BLOG_PAGE_FAILED = 'ADD_BLOG_PAGE_FAILED';

export const BLOG_SUBMITTED = 'BLOG_SUBMITTED';