export const ARTICLE_DRAFT_LOADING = 'ARTICLE_DRAFT_LOADING';
export const ARTICLE_DRAFT_LOADED = 'ARTICLE_DRAFT_LOADED';
export const ARTICLE_DRAFT_FAILED = 'ARTICLE_DRAFT_FAILED';

export const ARTICLE_DRAFT_POSTING = 'ARTICLE_DRAFT_POSTING';
export const NEW_ARTICLE_POSTED = 'NEW_ARTICLE_POSTED';