export const USER_PROFILE_LOADING = 'USER_PROFILE_LOADING';
export const USER_PROFILE_LOADED = 'USER_PROFILE_LOADED';
export const USER_PROFILE_FAILED = 'USER_PROFILE_FAILED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_NEWS_SUCCESS';