export const ARTICLE_PAGE_LOADING = 'ARTICLE_PAGE_LOADING';
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_FAILED = 'ARTICLE_PAGE_FAILED';

export const FETCHING_ARTICLE = 'FETCHING_ARTICLE';
export const GOT_ARTICLE = 'GOT_ARTICLE';
export const ARTICLE_FAILED = 'ARTICLE_FAILED';