export const ACCOUNT_PAGE_LOADING = 'ACCOUNT_PAGE_LOADING';
export const ACCOUNT_PAGE_LOADED = 'ACCOUNT_PAGE_LOADED';
export const ACCOUNT_PAGE_FAILED = 'ACCOUNT_PAGE_FAILED';
export const STORE_USER_PROFILE = 'STORE_USER_PROFILE';

export const PW_CHANGE_FORM_LOADING = 'PW_CHANGE_FORM_LOADING';
export const PW_CHANGE_FORM_LOADED = 'PW_CHANGE_FORM_LOADED';
export const PW_CHANGE_FORM_FAILED = 'PW_CHANGE_FORM_FAILED';

