export const DATAMAP_PAGE_LOADING = 'DATAMAP_PAGE_LOADING';
export const DATAMAP_PAGE_LOADED = 'DATAMAP_PAGE_LOADED';
export const DATAMAP_PAGE_FAILED = 'DATAMAP_PAGE_FAILED';
export const USER_CLICKED_MARKER = 'USER_CLICKED_MARKER';

export const DATAMAP_FETCHING_GIGS = 'DATAMAP_FETCHING_GIGS';
export const DATAMAP_GIGS_SUCCESS = 'DATAMAP_GIGS_SUCCESS';
export const DATAMAP_GIGS_FAILED = 'DATAMAP_GIGS_FAILED';

export const DATAMAP_FETCHING_FILTERS = 'DATAMAP_FETCHING_FILTERS';
export const DATAMAP_FILTERS_SUCCESS = 'DATAMAP_FILTERS_SUCCESS';
export const DATAMAP_FILTERS_FAILED = 'DATAMAP_FILTERS_FAILED';

export const USER_CLICKED_FILTER = 'USER_CLICKED_FILTER';
export const FILTER_BOOL_UPDATED = 'FILTER_BOOL_UPDATED';
export const GIGS_BEING_FILTERED = 'GIGS_BEING_FILTERED';
export const GIGS_FILTERED_DONE = 'GIGS_FILTERED_DONE';

export const SELECTED_GIG = 'SELECTED_GIG';