export const DATAMAP_PAGE_LOADING = 'DATAMAP_PAGE_LOADING';
export const DATAMAP_PAGE_LOADED = 'DATAMAP_PAGE_LOADED';
export const DATAMAP_PAGE_FAILED = 'DATAMAP_PAGE_FAILED';
export const USER_CLICKED_MARKER = 'USER_CLICKED_MARKER';
