export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_FAILED = 'HOME_PAGE_FAILED';

export const FETCH_NEWS = 'FETCH_NEWS';
export const FETCHING_NEWS = 'FETCHING_NEWS';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_FAIL = 'FETCH_NEWS_SUCCESS';